### ISSUE TITLE
it can contain usr/share ?

### ISSUE THREAD

**Issue by ringo32** [manjaro/desktop-settings#1]
i mean like : https://github.com/manjaro-nl/manjaro-mate-desktop-settings

dont need the Skell only, also other configuration ?

and install file need glib-compile-schemas ? or is it pure /skel ?

**Comment by oberon2007** [comment]
I agree, @ringo32 . In my understanding the idea is that the desktop-settings pkgs should offer a way to install the default user settings for a freshly created user on ISOs and maybe even on existing systems.
For that reason I think that the profiles of the Gnome family like Mate, Cinnamon, Deepin ... should deliver **/etc/skel** plus a file **/usr/share/glib-2.0/schemas/99_manjaro-default-gsettings.gschema.override**. An override like that would even make sense for other profiles. Also some Xfce- and other applications create their own dedicated gsettings path and can be customized that way.

**Comment by udeved** [comment]
No, but skel can contain skel/.local or skel/.icons

**Comment by udeved** [comment]
Well guys, we can't install wildly stuff in /usr/share if we can't make sure, no other package in the repos already provides a filename.
Hence, we need to see, but I think almost everything can be realized within skel.

skel is copied upon user creation.

**Comment by oberon2007** [comment]
It's not wildly installing stuff, just the way default config works in the gnome world. Default icon size of a file browser in traditional environments is defined in .config, in those DEs it's fine in/usr/share/glib-2.0 Adding this stuff in /skel simply doesn't work. Look at the suggested file name in my other comment. It's one file and it cannot conflict with any other file

**Comment by oberon2007** [comment]
Sorry accidentally hit the close button on my phone ;-) just wanted to paste the file name here again: 99_manjaro-default-gsettings.gschema.override

**Comment by ringo32** [comment]
mayby depend how you use the mate-settings.installl of the pkgbuild ,  have to see it first, im not feeling so well , so will see.... so as example : 

glib-compile-schemas --targetdir=/usr/share/glib-2.0/schemas ~/.local/usr/share/glib-2.0/schemas

i dont know if that works this is the end stuf.. to make that binblob to be stored in /usr/share/glib-2.0/schemas/'blob'

if that is possible then is skell also possible.

**Comment by ringo32** [comment]
you need to compile the blob otherwise is useless to store it.

**Comment by oberon2007** [comment]
**99_manjaro-default-gsettings.gschema.override** would not be a binary but a gschema file. - so easier to maintain... :)

**Comment by ringo32** [comment]
then it wont work :) it goes to a bin blob of glibc-schemas there is what it gona store there gnome based stuf dont use override it uses the blob atleast for mate or cinnamon

**Comment by oberon2007** [comment]
The overrides go into the bin blob and it will only be used when a new user is created, not existing users of course. But that's the same with changing stuff in /skel, it will also not affect existing $HOME config. Well I can only speak for deepin, but to me it looks exactly the same in all the Gnome babies. Maybe it's different. ;)

**Comment by ringo32** [comment]
the overrides dont go automatically in tho's blob... glib-compile-schemas is needed on mate depend i gues but it can be systemic as example if you change te sound or something else i dont know much about it..

**Comment by oberon2007** [comment]
Well, it's not enough that the override file is sitting there. The binary has to be recompiled by the package. Like that: https://github.com/manjaro/packages-community/blob/master/deepin-manjaro/deepin-desktop-schemas-manjaro/deepin-desktop-schemas-manjaro.install#L2

**Comment by ringo32** [comment]
think speak te same?

**Comment by oberon2007** [comment]
:)
