### ISSUE TITLE
Schemas Budgie

### ISSUE THREAD

**Issue by Ste74** [manjaro/desktop-settings#11]
Hi there..
![schermata del 2016-01-24 18-31-37](https://cloud.githubusercontent.com/assets/11218234/12537798/bcd8422e-c2c8-11e5-90e0-34ff9529e760.png)

Budgie not have schema ??

**Comment by ringo32** [comment]
mayby is like :+1: 
[org.solus-project.budgie-panel.applets.{WEIRD-code}]
alignment='start'
name='Icon Task List'
position='2'


but its possible has no Dconf for that, go to /usr/share/budgie-panel if there exist, look if there eventual a layout file exist... if so,  then must in dconf-editor a menu exist which layout it needed...

just use dconf and experiment bit by bit the gschema's... 

in this case its not org :)

you can find the id's :  
https://github.com/solus-project/budgie-desktop/blob/master/data/com.solus-project.budgie-panel.gschema.xml

think above comes close as example but not exact..

what is changed should be

Name='Value'

further above like

[com.solus-project.budgie-panel.panel]

thats the schema_id ,

i suppose enum_id comes under is you see on the link ?

**Comment by udeved** [comment]
Hi Ste,

I think you know more about Budgie than I do.
I have no idea if budgie uses glib schema.

**Comment by Ste74** [comment]
No i have just search a file .conf or .ini for budgie but not provide this version .. so search the key in repo solus on github

**Comment by ikeydoherty** [comment]
The default layout is baked in with the `panel.ini` file:
https://github.com/solus-project/budgie-desktop/blob/master/data/panel.ini

This will create the default panel layout and applet instances upon first run.
If you need support for a *vendor file* to overwrite this, I can easily add this.

We use relocatable schemas to give each applet and panel unique instance data within dconf, where "{WEIRD-code}" is actually a UUID. These should **not** be manually butchered.

Each applet that exposes a configuration of some sort does so via it's own gsettings, as an example: 

https://github.com/solus-project/budgie-desktop/blob/master/panel/applets/icon-tasklist/com.solus-project.icon-tasklist.gschema.xml

The Solus LiveCD overrides this by example, in `/usr/share/glib-2.0/schemas/com.solus-project.icon-tasklist.gschema.override`:

```ini
[com.solus-project.icon-tasklist]
pinned-launchers=['os-installer.desktop']
```

**Comment by Ste74** [comment]
Thank you friend for explain .. ;)

**Comment by udeved** [comment]
Can I close Stefano?

**Comment by Ste74** [comment]
Yes , i close by itself ;)

**Comment by ikeydoherty** [comment]
Please open a Budgie issue if you'd like support for a vendor file :)

**Comment by udeved** [comment]
I think we can do vendor files with schema-override files?

**Comment by ikeydoherty** [comment]
@udeved not for the `panel.ini` you can't :)

**Comment by Ste74** [comment]
You only need a file that you can overwrite or not?

**Comment by udeved** [comment]
The question is, do you need a customized panel.ini Ste?

**Comment by ikeydoherty** [comment]
^ Dude asks good questions :p

**Comment by udeved** [comment]
Dude is 20 years in business. :)

**Comment by ikeydoherty** [comment]
Fair play, dude. :p

**Comment by Ste74** [comment]
Depend .. If you see Rc1 is "vanilla" panel . If you see the picture at the first i have modified .. Moved app , add app .. changed the theme

**Comment by udeved** [comment]
The panel items are also defined in panel.ini?
Or is this part in dconf?

**Comment by Ste74** [comment]
i'm arbiter :)

**Comment by ikeydoherty** [comment]
So `panel.ini` is literally only for the first panel(s) layout, nothing more. If you want to override each applet config, well, that's actually down to the gsettings schema files

**Comment by udeved** [comment]
Yes, initialize panel with ini file, I thought so.

I think you can do rest in gsettings Ste, and use default layout?

**Comment by Ste74** [comment]
Ok .. i leave the default setting
