### ISSUE TITLE
community/i3/skel/.config/dunst/

### ISSUE THREAD

**Issue by pa-d-v** [manjaro/desktop-settings#115]
Some warnings of deprecated settings in dunst could be solved:
Warning: 'allow_markup' is deprecated since 1.2, please use 'markup' instead.
Warning: 'icon_folders' is deprecated since 1.3, please use 'icon_path' instead.
Warning: The frame section is deprecated since 1.2, width has been renamed to frame_width and moved to the global section.
Warning: The frame section is deprecated since 1.2, color has been renamed to frame_color and moved to the global section.

**Comment by oberon2007** [comment]
thank you!
