### ISSUE TITLE
Inconsistencies in Gnome Adapta-Nokto-Maia (Eta)

### ISSUE THREAD

**Issue by izznogooood** [manjaro/desktop-settings#119]
The window control bar and buttons have different sizes.

I switched to the Eta theme as this seems to have a more compact build, but some Window-Control-Buttons remain "large". In fact very large to my taste ;).

![scr_small_hover](https://user-images.githubusercontent.com/23040578/38636582-eb899370-3dc8-11e8-89fa-30effdeb0f9f.png)
![scr_big_hover](https://user-images.githubusercontent.com/23040578/38636586-f1075f1c-3dc8-11e8-8ebf-18a35ec6d9f0.png)

Im new to Manjaro and not sure if this is the right place or if I should open a ticket.

The large ones you see are Nautilus and  Tweaks, while Evolution (gtk) and Telegram (qt) are small (Normal)
It seems to affect "random" as Evolution and Nautilus are both GTK ?
Unless Evolution is now qt, then it would make more sense.

On a personal note, I have just found myself a new home. Great work!!!

**Comment by izznogooood** [comment]
Well that wont change:

https://github.com/adapta-project/adapta-gtk-theme/issues/679#event-1586625921

**Comment by Ste74** [comment]
@izznogooood sorry for delay, seem i have lost this issue but great to see you anyway find the right place where ask since adapta-maia is only adapta with maia color :wink:
