### ISSUE TITLE
live skel conflict in pantheon

### ISSUE THREAD

**Issue by Ste74** [manjaro/desktop-settings#12]
Hi guys , after more research found the problem : the shared pkg for livecd in pantheon create conflict .. how to proced ?

:: Proceed with installation? [Y/n] 
(71/71) checking keys in keyring                   [######################] 100%
(71/71) checking package integrity                 [######################] 100%
(71/71) loading package files                      [######################] 100%
(71/71) checking for file conflicts                [######################] 100%
error: failed to commit transaction (conflicting files)
manjaro-live-skel: /build/manjaro-tools/buildiso/pantheon/x86_64/live-image/etc/skel/.config/autostart/disable-dpms.desktop exists in filesystem
manjaro-live-skel: /build/manjaro-tools/buildiso/pantheon/x86_64/live-image/etc/skel/.config/autostart/live-session.desktop exists in filesystem
manjaro-live-skel: /build/manjaro-tools/buildiso/pantheon/x86_64/live-image/etc/skel/.config/autostart/pulseaudio-ctl.desktop exists in filesystem
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
  -> overlayfs: unmount live-image
==> ERROR: Exit make_image_live
[stefano@ste74 ~]$

**Comment by oberon2007** [comment]
Hi Ste! You have to remove these .desktop files from your desktop-settings pantheon! They are still in you **skel/.config/autostart**!! ;)

**Comment by Ste74** [comment]
off course @oberon2007 removed in my fork and pkg in a local repo to try a build but this file is present in shared livecd
https://github.com/manjaro/desktop-settings/tree/master/shared/live/skel/.config/autostart

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/commit/dd88aac6c34f9e121c719f3f00a9402687a7d5f6

**Comment by Ste74** [comment]
guys i have removed but i think buildiso found this in shared .. or not ? if i build a pkg for patheon setting and add in localrepo buildiso install it no ? ( offcourse i ahve correct source and release )

**Comment by philmmanjaro** [comment]
@Ste74: try again: https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160125/005724.html

**Comment by Ste74** [comment]
Same error :\

**Comment by udeved** [comment]
What branch are you building Ste?
You need unstable.

**Comment by Ste74** [comment]
Try today .. working..  :)
