### ISSUE TITLE
Add empty file for nautilus file manager to use new document option

### ISSUE THREAD

**Issue by Ste74** [manjaro/desktop-settings#14]
Hi all , is possible to add in $HOME/Template an empty file called example "new document" to obtain in nautilus menu the  new document option ? This is necessary for gnome and budgie 

https://wiki.archlinux.org/index.php/GNOME_Files#Create_an_empty_document_in_Files_3.6_and_above

**Comment by oberon2007** [comment]
Hah! cool! I'll do that too in Deepin :laughing:

**Comment by Ste74** [comment]
Correct also deepin use nautilus :-)

**Comment by oberon2007** [comment]
Oh. But the problem is localization! Like that it will only work on an English install! We'll need a more sophisticated solution...

**Comment by oberon2007** [comment]
Guess you'd have to install it via script to **XDG_TEMPLATES_DIR**

**Comment by Ste74** [comment]
Folder are localized ... i don't know if also one file is possible

**Comment by oberon2007** [comment]
You have to install it to **$(xdg-user-dir TEMPLATES)**

**Comment by oberon2007** [comment]
this should work:
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/2d65c436a16ff153413891753fdb5c1e6f570f94/community/deepin/deepin-overlay/usr/bin/create-template
plus
https://github.com/manjaro/desktop-settings/blob/c4e8bd190bce67ff0ba6bf6a405bbbbda28b4cd2/community/deepin/skel/.config/autostart/create-template.desktop

**Comment by oberon2007** [comment]
It works like that! :laughing: 
![empty_file](https://cloud.githubusercontent.com/assets/11800714/12699654/5d206a1e-c7c3-11e5-9618-ffcb9271899f.png)

**Comment by philmmanjaro** [comment]
Congrats.

**Comment by Ste74** [comment]
Thank you mate .. add it in gnome and budgie profile :smile:

**Comment by oberon2007** [comment]
Learning from the great ... ;)

How about cleaning up a little afterwards?
And ... is it ok for a script to remove itself? :laughing: 
```
rm $HOME/.config/autostart/create-template.desktop
rm /usr/bin/create-template
```
I was a little surprised that it is even possible :joy:

**Comment by oberon2007** [comment]
Ah well, but it's a bad idea anyway. We want the other users possibly created in the future to benefit from the 'Empty Files', too of course! ;)

**Comment by udeved** [comment]
We not the clean way, and provide /usr/bin/create-template and /etc/skel/.config/autostart/create-template.desktop with a package? ;)

**Comment by udeved** [comment]
Would make even more sense to do a package, if you can share in for several DEs, instead of dropping it on iso fs per profile.

**Comment by oberon2007** [comment]
You are right of course! I'll do that! :)

**Comment by philmmanjaro** [comment]
Providing it as a package would be best here.

**Comment by oberon2007** [comment]
:+1:

**Comment by udeved** [comment]
I can expand the build, I just need to know what DEs make use of it, we can make it depend on provide packages, ie settings packages.

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/commit/bb2c0065dc9faa414bc609d2dd67602d21671aaf

**Comment by oberon2007** [comment]
Cool! Sofar we know that Gnome, Budgie and Deepin need that. Cinnamon apparently doesn't need it.
We still need to find out about Pantheon and Mate now. @Ste74 @ringo32 ?

**Comment by udeved** [comment]
What about mate-gtk3 btw?
I started a mate-gtk3 minimal profile.

**Comment by Ste74** [comment]
hi guys, no pantheon use another file manager , not needed this :)

**Comment by ringo32** [comment]
first of all mate-gtk3 is a bit experimental, next mate would be gtk3 anyway whats use of minimal profile ? only mate package with out mate other extra stuf ?

what makes it minimal ? its not mate that the iso made 1.6gb only, and i dislike personal to switch of lib32..

**Comment by ringo32** [comment]
it also redudant all minimal profiles...

**Comment by udeved** [comment]
@ringo32

I started mate-gtk profile so you could probably prepare transition to mate-gtk.
I also indeed hate this huge package list in mate profile if I need to quickly build mate iso.

**Comment by ringo32** [comment]
i see no use of mate-gtk3 personally , for moment experimenting with gschemas and limitationall seems ok only not terminal  :p but i try to put those in /etc/dconf for experiment and do dconf dump /org/mate > database ,  the /etc/dconf can also used for ibus it seems

**Comment by ringo32** [comment]
but gnome tells /etc/dconf is unstable, but on fedora xfce see it suck thing in /etc/dconf
