### ISSUE TITLE
Guideline for desktop-packages and iso-profiles

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#15]
I add some raw draft of a guideline here, we can develop further.
### iso structure
- The ideal iso should leave no files left if you hypothetically uninstalled all packages.
  Perhaps some /etc/_.pac_ files would be left for example.
  The point is, only deploy files in the iso-profiles repo, that already belong to a package.
  Best practice would be, if you use the iso-profiles overlay only to configure system wide tsettings
  
  /etc/*.conf
  /etc/foo/bar.conf

All the rest can normally be deployed in the desktop-settings repo

We can always introduce new folder structure easy to navigate for packaging.

**Comment by philmmanjaro** [comment]
Obsolete
