### ISSUE TITLE
Profile and settings removal

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#16]
Guys, I will delete fluxbox, bspwm, openbox, jmw from profiles and settings.
These profiles don't seem to be updated in our repos rather than in forks.

If the maintainers want them included again, please send pull requests.

@oberon2007 

What about i3? Do you work on i3 iso? Have you found a wirkaround for live session?

**Comment by oberon2007** [comment]
i3 is still active. Will work on the details later again for 16.03

**Comment by oberon2007** [comment]
Will the current state of fluxbox be preserved somwhere?

**Comment by oberon2007** [comment]
**bspwm** is actively being maintained by @Chrysostomus ! Should definitely not be removed. @holmeslinux said that he's going to do openbox again.

**Comment by udeved** [comment]
Yes, we got 15.12 branch, we got it in pkg format, and I have it mirrored on my github. ;)

They need to send pull requests. I removed them, otherwise we probably won't meet 16.03 with the many packages.
WMs can be added later, once we got the DEs stable.

**Comment by Chrysostomus** [comment]
I'll send the request. It won't merge automatically now though, but maybe I can rebase around current master first...

Bspwm edition is now undergoing biggest change since swithing to gtk3. The latest updates to bspwm have introduced breaking syntax changes in configuration. That's why I have been avoiding sending pull request with half baked updates, as I'm still testing the new cofiguration required by updated bspwm. But it is now quite usable already.

**Comment by oberon2007** [comment]
You can just copy youre bspwm folders too a safe place, then git pull or even a fresh git clone and copy them back in... Shouldn't be a problem to push or merge then.

**Comment by Chrysostomus** [comment]
Yeah, that's what I was thinking pretty much.

**Comment by oberon2007** [comment]
I would simply delete the fork and make a new one afterwards ;)

**Comment by ringo32** [comment]
this case you can remove mate profile

**Comment by Esclapion** [comment]
lxqt, lxde, and e19 profiles also

**Comment by udeved** [comment]
I just removed the mentioned stuff, just so we get feedback, which was non existent so far.
I see no reason to remove lxde, lxqt and mate.
On lxqt, I would really appreciate, if we could find a common ground for lxqt and lxqt-minimal in relation to artwork.
I generally would prefer that manjaro developed a standard theme, eg maia.
We spread so thin with this very individualized editions, we lack people for that.

For example, I asked Holmes several times for the source url of his artworks stuff to be packaged, but no answer yet.

**Comment by ringo32** [comment]
community releases are stil no official releases.

**Comment by philmmanjaro** [comment]
We always have the issue with community editions that they don't follow our development cycles. Removing unmaintained stuff makes sense from a development point of view. We have to see how we deal with community editions in the future. How to promote them and how to deal with download links.

Lets have a meeting about it soon.

**Comment by udeved** [comment]
We need a decision how we handle community.
