### ISSUE TITLE
skel packages that need rebuild for iso release

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#2]
### official
- [ ] xfce
- [ ] kde

### minimal
- [ ] lxqt
- [ ] budgie
- [ ] kde
- [ ] xfce

### community
- [ ] bspwm
- [ ] cinnamon
- [ ] enlightenment
- [ ] gnome
- [ ] jwm
- [ ] lxqt
- [ ] netbook
- [ ] pantheon
- [ ] budgie
- [ ] deepin
- [ ] fluxbox
- [ ] i3
- [ ] lxde
- [ ] mate
- [ ] openbox
- [ ] gnome-sonar
- [ ] mate-sonar
- [ ] firefox

**Comment by udeved** [comment]
The [PKGBUILD] (https://github.com/manjaro/packages-extra/blob/master/desktop-settings/PKGBUILD) for desktop-settings.

**Comment by oberon2007** [comment]
I will just update mine every time they are in a usable state. :)

**Comment by udeved** [comment]
I tried for the moment to keep it all in one pkgbuild.
We may think about splitting out some packages in separate build later.

For example, we can probably have a skel pkg that only provides the (dot) files, if they are shared by almost all profiles.

**Comment by udeved** [comment]
Btw, I need to read up on markdown in github more.
I think its possible to update this list from commits.
One can place markdown in commit messages I read.

**Comment by udeved** [comment]
The idea behind packages in broader sense, we perhaps can get almost rid of iso-profiles, generate them on the fly by specifying the DE. 
The skel packages could serve as meta packages, that pul in the stuff they provide settings for, ie it would reduce iso-profiles to basically a list of additional apps.

**Comment by ringo32** [comment]
and if someone want too build a own costumized iso ?

**Comment by udeved** [comment]
he develops a skel and put his skel on pull request so it can be packaged and used in his profile's pkglist

**Comment by ringo32** [comment]
personally  i find it evil this way

**Comment by udeved** [comment]
Why, you shoud work on the mate or cinnamon skel if possible, profiles use it. :)
You don't need to package it, just work in there.

**Comment by udeved** [comment]
The team need to work together as team, its too cluttered in my view.

**Comment by ringo32** [comment]
personal community = community is just for fun if want to do try out something dont need to push things.. ?
as for official is also other buisness.. Xfce need mmore love on support and application etc.. its now a second rang desktop in my eyes.. if it does build this way for xfce kde is fine,..

**Comment by udeved** [comment]
Don't get me wrong, but I find it strange that a core team member is very reluctant to work in the repos.
