### ISSUE TITLE
~.i3/config in live-environment

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#22]
i3 needs a different file **~.i3/config** in live than in the final install for several reasons (autostarted applications, conky showing the shortcut for installer and config for the installers themselves...)
How can I achive that with the new structure? Does **manjaro-tools** still support a live-overlay and if yes, where do I place that file?

**Comment by philmmanjaro** [comment]
Nothing has changed in regard of overlay. simply put it as usual into the **/etc/skel** folder in your project. And for live-session I really don't care that we have there some skel files. Only for installed systems it would be nice if it was packaged in a settings file.

**Comment by oberon2007** [comment]
Ok. Thanks :-)
