### ISSUE TITLE
success !!

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#25]
Thank you, @udeved for pestering all of us with this new concept! :laughing: 
https://forum.manjaro.org/index.php?topic=31426.msg258371#msg258371
This is brilliant!

**Comment by oberon2007** [comment]
Since **manjaro-cinnamon-settings** is now a fine working package obvioulsy, it would be nice to add the required [dependencies](https://forum.manjaro.org/index.php?topic=31426.msg258366#msg258366) Maybe should I create a separate package then or do you not mind to have these installed in your chroot?

**Comment by oberon2007** [comment]
I'll added the depends in the multi-package. Really no big deal in download-size, I think:
**artwork-cinnamon-minimal** is less than 1MB, gtk and xcursor theme are small. The only bigger one is **maia-icon-theme**, but that one everybody will have installed in their chroot already anyway and **cantarell-fonts** aswell... ;)

**Comment by udeved** [comment]
Yep, add the proper depends what the settings package requires.

For example, it may also be possible that you let your cinnamon depend on the cinnamon-minimal, so you may be able to reduce maintaining efforts. Usually, these two packages provide more or less same stuff, just one adds additional bits.

**Comment by oberon2007** [comment]
have a look. :) settings are just the same, the only differences in the full version are in packages.
