### ISSUE TITLE
How to add depends on a specific package?

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/desktop-settings#28]
Would be nice to make the manjaro-bspwm-settings package depend on certain core packages of the edition. Also, current description of the package is "Manjaro Linux budgie settings".

Where can I fix these?

**Comment by Ste74** [comment]
You mean this ?
https://github.com/manjaro/packages-extra/tree/master/manjaro-desktop-settings

**Comment by udeved** [comment]
https://github.com/manjaro/packages-community/tree/master/desktop-settings-community

This is the build containing bspwm.

**Comment by Chrysostomus** [comment]
Thanks
