### ISSUE TITLE
xfce settings

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#37]
Can the xfce settings please be moved to its own repo?
I'd like to do some cleanup on PKGBUILD, and start with adding depends.
Would be nice to drop the build in extra then, and move left overs to community.

**Comment by philmmanjaro** [comment]
Yes, why not: https://github.com/manjaro/manjaro-xfce-settings

**Comment by udeved** [comment]
Do we already have a manjaro-kde-settings build since it was split out?
Could xfce depend on xfce-minimal?

**Comment by udeved** [comment]
https://github.com/manjaro/packages-community/commit/7aa4c59adb920b508133786bf2f4605a8ab93615

Its in community, found it.

**Comment by philmmanjaro** [comment]
We have other browsers in minimal. However we can create a manjaro-xfce-base-settings package which both settings packages can depend on. We should do a diff and simply put the common stuff into base.

**Comment by udeved** [comment]
Or have distict browser settings for each browser? Decouple profile from browser?

**Comment by philmmanjaro** [comment]
I'm sure we will find a solution. Simply check what the current diff is.

**Comment by udeved** [comment]
Its not much, its more additional app settings I think.

If we consequently add depends to settings packages, the iso-profile's Packages-<DE> will be more or less empty. :)

**Comment by philmmanjaro** [comment]
Well, the settings are for the packages we use. In this case more for themeing. I think they are not so much deps after all.

**Comment by udeved** [comment]
Ok, so what about meta packages we could use for pkglist?

If we could find a way to control the DE layer via package depends, the list became obsolete, and DM could be entirely set up by buildiso.

**Comment by philmmanjaro** [comment]
Lets do it step by step. It should be reasonable also. We can look over to Antergos and see how they manage to install their DEs with **Cnchi**.

**Comment by udeved** [comment]
There is no hurry with this, I bet they use meta packages to select, or static list that pulls packages.
