### ISSUE TITLE
[i3] .extend.bashrc is not applied

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#39]
As the title says.
What am I missing?

**Comment by oberon2007** [comment]
@udeved I remember dimly that you had posted a link about this when you created these files. But I cannot find it anywhere now. How is the content of **.extend.bashrc** supposed to be applied? Is this working for you @Chrysostomus ?

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/blob/master/shared/bash/.bash_profile

Look here, its in manjaro-base-skel

**Comment by oberon2007** [comment]
This **~/.bash_profile** is present on the image. But the aliases defined in **.extended.bashrc** are not working... Something must be missing here.

**Comment by udeved** [comment]
Try to source the extend in the /etc/skel/.bashrc

**Comment by oberon2007** [comment]
That would work, yes!

**Comment by oberon2007** [comment]
Looks like my **~/.bash_profile** is not being sourced, right? From where's that supposed to happen?

**Comment by oberon2007** [comment]
Ok. Thanks. :)

**Comment by udeved** [comment]
I'll move some bashrc stuff in a default ,extend.bashrc that will be in the profiles.

**Comment by udeved** [comment]
Bernhard, you need to adopt from the .extend.bashrc what you want and need.
I moved colourization in the extend, see shared/bash/.bashrc

**Comment by oberon2007** [comment]
Alles klar!
