### ISSUE TITLE
manjaro-<desktop>-settings has some file conflicts

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/desktop-settings#4]
Seems there is still some work to do ...

```
error: failed to commit transaction (conflicting files)
/var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.config/autostart/manjaro-welcome.desktop exists in both 'manjaro-kde-minimal-settings' and 'manjaro-welcome'
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.Xresources exists in filesystem
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.bash_profile exists in filesystem
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.bashrc exists in filesystem
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.conkyrc exists in filesystem
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.dir_colors exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by udeved** [comment]
Yes, the dot files, they need to be cleaned up and possibly packed up or used in overlay.
I think we need a strategy here.

**Comment by philmmanjaro** [comment]
**root-overlay** has followed files:

```
tree -a skel
skel
├── .bashrc
├── .conkyrc
├── .dir_colors
├── .mozilla
│   └── firefox
│       ├── 9shb6xj3.default
│       │   ├── bookmarkbackups
│       │   │   └── bookmarks-2013-03-04.json
│       │   ├── chrome
│       │   │   └── userChrome.css
│       │   └── prefs.js
│       └── profiles.ini
└── .Xresources

5 directories, 8 files
```

**Comment by udeved** [comment]
the mozilla should go.
I just don't know if at all, the various .mozilla folders are necessary, if they just provide manjaro bookmarks for example.
A firefox-settings package is on ToDo.

**Comment by philmmanjaro** [comment]
So best is to provide skel with the desktop settings and not with **root-overlay**.

**Comment by udeved** [comment]
Yes, I think so. I just didn't clean the shared/manjaro/* yet.

**Comment by udeved** [comment]
Basically, if in overlay, its meaningless, if in root-overlay or desktop-overlay.
Just that desktop-overlay overwrites root-overlay stuff.
So in a sense pointless to have skel in root-overlay, except we only gonna have a root-image and no desktop-image

**Comment by philmmanjaro** [comment]
Ok, then copy those skel files into the desktop-settings from root and if it already provides some, skip them. **xfce-minimal** seems to be fine so far.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/dbd8ed7ae83ac8fbffb6f625901600092b14b5ad

**Comment by udeved** [comment]
Btw, we should have one iso out before annoucning settings packages.
Noobs will find it hard to figure out that they need to clean /etc/skel if installed pre 16.01

**Comment by philmmanjaro** [comment]
Now we have still this:
```
error: failed to commit transaction (conflicting files)
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.bash_profile exists in filesystem
manjaro-kde-minimal-settings: /var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/kde-image/etc/skel/.bashrc exists in filesystem
```

**Comment by udeved** [comment]
bashrv and bash_profile are provided by package bash, I guess?

I wish we had pkgfile for this.

**Comment by philmmanjaro** [comment]
I think it is e513b08db0acdd22c879282cdb3eda0fa5a341ee

**Comment by udeved** [comment]
wait a minute, I will chroot in the arch system to run pkgfile. We can check.

Did you add manjaro-base-skel to your list?

**Comment by udeved** [comment]
~~~
pkgfile .bash_profile
core/bash

pkgfile .bashrc
core/bash
~~~

So we either do manjaro bash package or we do it in overlay, which is not update safe.

**Comment by philmmanjaro** [comment]
hmm. or remove those files from our desktop-settings ... hmm

**Comment by philmmanjaro** [comment]
I have it. We do a install scriplet ...

**Comment by udeved** [comment]
Whatever we do, if we use arch bash package, we can't package those files, and probably a few more.

**Comment by philmmanjaro** [comment]
let me check the **bash** package then.

**Comment by udeved** [comment]
It all depends what lands on a default installed arch system in /etc/skel.

This is on arch without any DE, just base group install:

~~~
ls -a /etc/skel
.  ..  .bash_logout  .bash_profile  .bashrc
~~~

**Comment by philmmanjaro** [comment]
Yep ...
```
  # user configuration file skeletons
  install -m644 dot.bashrc "$pkgdir"/etc/skel/.bashrc
  install -m644 dot.bash_profile "$pkgdir"/etc/skel/.bash_profile
  install -m644 dot.bash_logout "$pkgdir"/etc/skel/.bash_logout
```

**Comment by udeved** [comment]
Question is, do we want a manjaro bash?
Is it desirable considering readline etc?

**Comment by philmmanjaro** [comment]
Let me quickly test something first.

**Comment by philmmanjaro** [comment]
Currently we have this:
```
desktop-settings]$ ls */*/skel/.bash*
community/bspwm/skel/.bash_profile  community/mate/skel/.bash_profile
community/bspwm/skel/.bashrc        community/mate/skel/.bashrc
community/deepin/skel/.bashrc       community/openbox/skel/.bashrc
community/fluxbox/skel/.bashrc      minimal/kde/skel/.bash_profile
community/i3/skel/.bashrc           minimal/kde/skel/.bashrc
community/jwm/skel/.bashrc          official/kde/skel/.bash_profile
community/lxde/skel/.bashrc         official/kde/skel/.bashrc
community/lxqt/skel/.bashrc
```
Let me check something here.

**Comment by udeved** [comment]
We need to diff many files in the process I think, to see if they are relly necessary.
On the positive side, we create very solid profiles.

**Comment by philmmanjaro** [comment]
Let me do something first before dropping it from **bash**.

**Comment by udeved** [comment]
Sure, no haste, this is the tricky part to sort this all out.

**Comment by oberon2007** [comment]
FYI, I am using a customized **.bashrc**. If that's a problem I can drop it.

**Comment by philmmanjaro** [comment]
@oberon2007: working on it ...

**Comment by udeved** [comment]
Currently checking some files ...

~~~
pkgfile .zshrc   
extra/grml-zsh-config
~~~

Only other is .zshrc.

**Comment by philmmanjaro** [comment]
For now only at:
```
ls */*/skel/.zsh*
community/bspwm/skel/.zshrc
```

**Comment by udeved** [comment]
In summary, bash and zsh, so the shells need to be handled.

**Comment by udeved** [comment]
~~~
pkgfile -ds /etc/skel/       
core/bash
core/filesystem
extra/grml-zsh-config
extra/screen
community/mksh
community/xombrero
~~~

**Comment by philmmanjaro** [comment]
**grml-zsh-config** is used by **archboot**, so no issue on our end.

**Comment by udeved** [comment]
filesystem only provides /etc/skel
no issue there either.

**Comment by udeved** [comment]
~~~
$ sudo pacman -Syu manjaro-base-skel
:: Synchronisiere Paketdatenbanken...
 core ist aktuell
 extra                                     1919,6 KiB   643K/s 00:03 [######################################] 100%
 community ist aktuell
 multilib ist aktuell
:: Starte vollständige Systemaktualisierung...
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (2) manjaro-lxqt-minimal-settings-20160112-5  manjaro-base-skel-20160112-5

Gesamtgröße des Downloads:                0,02 MiB
Gesamtgröße der zu installierenden Pakete:  0,14 MiB
Größendifferenz der Aktualisierung:       0,02 MiB

:: Installation fortsetzen? [J/n] j
:: Empfange Pakete...
 manjaro-base-skel-20160112-5-any             4,7 KiB  93,2K/s 00:00 [######################################]  21%
 manjaro-lxqt-minimal-settings-2016011...    21,3 KiB   125K/s 00:00 [######################################] 100%
(2/2) Prüfe Schlüssel im Schlüsselring                               [######################################] 100%
(2/2) Überprüfe Paket-Integrität                                     [######################################] 100%
(2/2) Lade Paket-Dateien                                             [######################################] 100%
(2/2) Prüfe auf Dateikonflikte                                       [######################################] 100%
(2/2) Überprüfe verfügbaren Festplattenspeicher                      [######################################] 100%
(1/2) Installiere manjaro-base-skel                                  [######################################] 100%
cp: der Aufruf von stat für „/etc/skel/bash/*“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Fehler: Befehl konnte nicht korrekt ausgeführt werden
(2/2) Aktualisiere manjaro-lxqt-minimal-settings                     [######################################] 100%
cp: der Aufruf von stat für „/etc/skel/bash/*“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Fehler: Befehl konnte nicht korrekt ausgeführt werden
~~~

**Comment by udeved** [comment]
Perhaps best in this case to move the bashrc back in profiles as only exception.
pacman should make a backup, so its not totally lost after update of bash,

I can do it, sleep well.

**Comment by udeved** [comment]
even better, lets install the base skel not in /etc but somewhere in /usr/share/manjaro(-tools)

This way, the bash folder in skel doesn't get copied to home dir too.

**Comment by philmmanjaro** [comment]
Well, the current way is working. I'm open for better ideas. Simply WOW me ;)

**Comment by udeved** [comment]
Oh Efendi, the Sultan thinks installing the bashrc eg in /usr/share/bash/bashrc.manjaro
 get us rid of the /etc/bash folder. The camel can be copied from install location to /etc/skel. 
so only slight modification of the silk road. :)

**Comment by philmmanjaro** [comment]
Hmm, makes sense, this will avoid the copying of the **bash** folder to the home-dir. Go for it ...

**Comment by udeved** [comment]
Right, I'll commit the mod soon.

**Comment by udeved** [comment]
Would be nice opportunity to perhaps include source the msg functions from manjaro-tools in bashrc and zshrc so they are always accessible?

**Comment by udeved** [comment]
what are we gonna do with the overlay/root/etc/skel stuff that is in the profiles still?

I do see the need for live overlay skel files.

**Comment by oberon2007** [comment]
Some config for root is needed in i3 and fluxbox because the root account is otherwise practically not useable. My understanding is that /etc/skel is not copied over to /root's home, or is it? Anyway would that be an option?

**Comment by udeved** [comment]
I haven't touched the stuff in live-overlay/{root,/etc/skel}.
You are right, skel doesn't apply for root.

I think we can package the /root folder stuff thats not in live-overlay.
live-overlay/{root,/etc/skel}. can remain, I believe should remain.

**Comment by oberon2007** [comment]
Can /root/ not really just be a copy of /etc/skel ?

**Comment by udeved** [comment]
Well, it depends what you deploy in /etc/skel, its a potential security hole.

**Comment by udeved** [comment]
We need to rething /root

from livecd script in manjaro-tools, that is run before live session starts:

~~~
cp -a /etc/skel/. /root/
~~~

This may solve some mystery, why some live-overlay/root stuff doesn't work, it gets overwritten eventually.

**Comment by udeved** [comment]
I think Stefano has done the dconf schema stuff well.
Pantheon could be reference for schema stuff.

I will further clean profiles, so we end up with entire user customization of profile being in desktop-settings. Stuff is already pretty much transferred in their respective skel folders.

@oberon2007  
I cleaned up your profiles a bit, perhaps it becomes now more clear what is possible, and what may confused. ;)

**Comment by oberon2007** [comment]
Yes. I've commented there. But it will only work if you copy the desktop settings to /root. Otherwise you make the root account unusable in a WM. There is no default funcionality.

**Comment by udeved** [comment]
What I am saying, there was kind of bug, flawed logic how we set up /root folder @oberon2007 ;)
Especially if you use a real root-overlay folder instead of symlink, it may have affected several profiles.
https://github.com/manjaro/manjaro-tools/commit/fa7b52de24c76ccacca1232706ddb420dde59108

**Comment by udeved** [comment]
Regarding the /root folder.

We could set it up like this:

~~~
if [ -d $srcdir/$pkgbase/$1/root ]; then
		cp -r $srcdir/$pkgbase/$1/root/. $pkgdir/root
else
		cp -r $srcdir/$pkgbase/$1/skel/. $pkgdir/root
fi
~~~

Is this desirable? Is there any need for special /root setup that differs from /etc/skel?

**Comment by udeved** [comment]
I haven't look enough at xfce and kde yet.
But could me make eg manjaro-kde-settings depend on manjaro-kde-minimal-settings?
Same for xfce.

Won't work for lxqt, I had to talk to Esclapion to coordinate theming, they are different.

**Comment by oberon2007** [comment]
maybe put **.xinitrc** in the backup array? Otherwise you will not be able to install **desktop-settings** in on an existing system.

**Comment by oberon2007** [comment]
rubbish. forget what i just said! :laughing:

**Comment by udeved** [comment]
Any iso built with settings pkg will have a clean /etc/skel, and stuff in there can be simply removed.
I used to be part of filesystem, which was not so good.

Bernhard, don't wonder, I removed for the moment your live skel customization from the profiles.
We can move them back if we don't find a good solution. I was thinking we may be able to come up with something for all the WM based iso.

**Comment by oberon2007** [comment]
for fun I was just trying to install **manjaro-xfce-settings** on my deepin install and /etc/skel/.xinitrc was the only conflicting file of course ;)

**Comment by udeved** [comment]
Best is, you simply rm -r /etc/skel/* on existing install.

**Comment by oberon2007** [comment]
yes sure. no problem :)

**Comment by udeved** [comment]
Do these WM editions need necessarily the live menu, or would be destop symlinks to the apps enough?

**Comment by oberon2007** [comment]
you mean i3 and fluxbox? no. they don't support desktop icons! ;) and in i3 the whole WM only works with the config and the conky serves as a cheat-sheat for the shortcuts. people will be lost without it to launch the installers...

**Comment by udeved** [comment]
I see, damn those WMs. ;)

**Comment by oberon2007** [comment]
::)

**Comment by udeved** [comment]
But on a serious note, these WMs screw pretty much up some nice idea.

**Comment by udeved** [comment]
What about dynamic menus for these?

**Comment by oberon2007** [comment]
Nope ... doesn't exist. That stuff sucks! :laughing:

**Comment by oberon2007** [comment]
So, I just installed **manjaro-xfce-settings** plus some packages from **Packages-Xfce** on m Deepin install here. It took about 2 minutes... This is TOTALLY fun!! :laughing: 
![xfce](https://cloud.githubusercontent.com/assets/11800714/12367008/490c823c-bbdf-11e5-83db-06db77f6e2d1.png)

**Comment by udeved** [comment]
Yes, we can now simulate the iso easily on the system. :)

**Comment by philmmanjaro** [comment]
So we are now on the stage to give the user the option to install our desktops with our settings as it should be. Great. Next step would be to add a module to Calamares to choose the available desktops and create a network install media with Calamares starting up in fullscreen. Maybe a minimal LxQt live.

**Comment by oberon2007** [comment]
Who wants to go completely crazy can create a meta-package of the needed packages for his profile. Then people can really just install a second default desktop to their systems :laughing:

**Comment by Ste74** [comment]
Pantheon desktop settings seems problem
![schermata del 2016-01-21 22-18-36](https://cloud.githubusercontent.com/assets/11218234/12495017/96c4bce4-c08d-11e5-8f90-886afdb78259.png)

**Comment by Ste74** [comment]
Correct the conflicts and try to rebuild but desktop-settings is online ? Only when pushed in repo i can rebuild ?
