### ISSUE TITLE
how to get config to root's home

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#40]
What's the way to add configuration for the root account?
In i3 a config file is needed to make a session as root work and also gtk-theming and icons for applications launched with pkexec are the default Adwaita and don't match the rest.

**Comment by oberon2007** [comment]
Could we not just have the content of **/etc/skel** copied to **/root** also?

**Comment by oberon2007** [comment]
I guess it will have to be done either in the profiles or by a separate package. For existing installs it doesn't make sense and will not work anyway...

**Comment by udeved** [comment]
I would have security concerns to "unlock" copying full skel to /root.

I think you need to configure sudo properly for your i3. Look at /etc/sudoers

**Comment by oberon2007** [comment]
How do you mean configure sudo? How would that make config available for the root account?

**Comment by udeved** [comment]
See the X settings in /etc/sudoers

**Comment by udeved** [comment]
~~~
## Run X applications through sudo; HOME is used to find the
## .Xauthority file.  Note that other programs use HOME to find   
## configuration files and this may lead to privilege escalation!
# Defaults env_keep += "HOME"
##
## X11 resource path settings
# Defaults env_keep += "XAPPLRESDIR XFILESEARCHPATH XUSERFILESEARCHPATH"
##
## Desktop path settings
# Defaults env_keep += "QTDIR KDEDIR"
##
## Allow sudo-run commands to inherit the callers' ConsoleKit session
# Defaults env_keep += "XDG_SESSION_COOKIE"
##
## Uncomment to enable special input methods.  Care should be taken as
## this may allow users to subvert the command being run via sudo.
# Defaults env_keep += "XMODIFIERS GTK_IM_MODULE QT_IM_MODULE QT_IM_SWITCHER"
~~~

    man sudoers

;)

**Comment by oberon2007** [comment]
Ok, this may help for applications run with sudo. Will try that later.
But still thus won't provide a functional root account to log into a i3 session I'm afraid...

Am 10. März 2016 18:40:54 MEZ, schrieb udeved <notifications@github.com>:
>~~~
>## Run X applications through sudo; HOME is used to find the
>## .Xauthority file.  Note that other programs use HOME to find   
>## configuration files and this may lead to privilege escalation!
># Defaults env_keep += "HOME"
>##
>## X11 resource path settings
># Defaults env_keep += "XAPPLRESDIR XFILESEARCHPATH
>XUSERFILESEARCHPATH"
>##
>## Desktop path settings
># Defaults env_keep += "QTDIR KDEDIR"
>##
>## Allow sudo-run commands to inherit the callers' ConsoleKit session
># Defaults env_keep += "XDG_SESSION_COOKIE"
>##
>## Uncomment to enable special input methods.  Care should be taken as
>## this may allow users to subvert the command being run via sudo.
># Defaults env_keep += "XMODIFIERS GTK_IM_MODULE QT_IM_MODULE
>QT_IM_SWITCHER"
>~~~
>
>    man sudoers
>
>;)
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/desktop-settings/issues/40#issuecomment-194971759

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by udeved** [comment]
I don't understand, why gui application do you need to run as root?
Why isn't sudo sufficient? Normally, you don't run gui apps as root, its no good security wise.

**Comment by oberon2007** [comment]
What I mean is offering the possibility to log into a graphical i3 session with root account - it's maybe superfluous...

Am 10. März 2016 19:45:26 MEZ, schrieb udeved <notifications@github.com>:
>I don't understand, why gui application do you need to run as root?
>Why isn't sudo sufficient? Normally, you don't run gui apps as root,
>its no good security wise.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/desktop-settings/issues/40#issuecomment-194996916

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by udeved** [comment]
Thats normally a big nono and discouraged by system admins.
Some distros even disable graphical root login.

**Comment by oberon2007** [comment]
Ok, I see. Then that's out. I will experiment now with the sudo / pkexec theming stuff ...

**Comment by udeved** [comment]
On a side note, there is really no need to login as root inn a DM session.
You can use su command if you like instead of sudo.
su login runs stuff as root, whereas sudo escalates privileges.

    man su

**Comment by oberon2007** [comment]
Yes, understood :)

**Comment by ringo32** [comment]
@oberon and what is the /etc/i3/ there is also some base settings ?

**Comment by oberon2007** [comment]
@ringo32 they are just the templates that will be copied to $HOME when you auto-create i3 config on first run :wink:
I will just fix the theming for sudo now and leave the root account alone :)

**Comment by oberon2007** [comment]
Ok. So uncommenting ``Defaults env_keep += "HOME"`` in **/etc/sudoers** fixes the theming for sudo and gksu. But now the question is how to achieve that? The file is owned by package **sudo** ...

**Comment by oberon2007** [comment]
Hah, maybe I'm just thinking to complicated? I should simply be able to set global theming and icons in **/etc/gtk-2.0/gtkrc** and **/etc/gtk-3.0/settings.ini**, right? :stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
Works perfectly! :laughing:
@holmeslinux I assume this might be the solution for your root applications' theming, too :stuck_out_tongue_winking_eye: : https://github.com/manjaro/manjaro-tools-iso-profiles/commit/94db7a991c8a3c7c293bcc9617edef8fa8f41e55
