### ISSUE TITLE
Sonar desktop settings are bad implented (mate)

### ISSUE THREAD

**Issue by ringo32** [manjaro/desktop-settings#45]
dont know where you find those schemes this schemas should work : 

https://github.com/ringo32/desktop-settings/tree/devel/community/mate/share/glib-2.0/schemas

as example

**Comment by ringo32** [comment]
its just pity to see, that configs is pointing to somewhere but implent things that dont work properly..

**Comment by coffeeking** [comment]
hi
I wrote a lot of this by hand, taken from dconf editor. Did I screw up
the keyboard shortcuts yet again? I ran the schema through
glib-compile-schemas and it didn't print any errors or warnings. There
really has to be a way to make doing this kind of thing easier. I'm at
an impass right now. Lightdm *will not* start on the live image, and no
one seems to know what's wrong.
Thanks
Kendell Clark


ringo32 wrote:

**Comment by coffeeking** [comment]
hi
You are going to have to be more specific. What is being pointed at that
doesn't exist or work properly. I can't fix it unless I know what to fix.

ringo32 wrote:

**Comment by coffeeking** [comment]
hi ringo
Thanks for fixing the schema. I'll murge this into sonar's desktop settings.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by ringo32** [comment]
yeah as wallpaper as example : 

[org.mate.background]
picture-filename='/usr/share/backgrounds/manjaro.jpg'

on this github is very different, personal i like to have bits of pieces had once in one file, but it didnt act somehow as expected..if i do in parts it did work somehow..

further , you cannot copy 1 on one i have as example mate menu.. (fork mint menu)

saw the iso was bit standard ( that green wallpaper)

if you peak intoo dconf-editor

in terminal you do dconf dump /org   > dumped.txt    as example you can easier copy and paste...
only minor is the 'DOT' in override is /

example : 

dconf dump gives : 

[virt-manager/virt-manager]
manager-window-height=550

in override could be : 

[virt-manager.virt-manager]
manager-window-height=550



that can differ..

hope helped a bit :)

**Comment by coffeeking** [comment]
hi
Ah. I think I understand now. The schema was trying to set the
background as /usr/share/backgrounds/sonar.png, but there was no png
file, only a jpg file, so I changed it.
Thanks
Kendell Clark


ringo32 wrote:

**Comment by ringo32** [comment]
your background looks : 

[org.mate.desktop.background]
picture-filename="/usr/share/backgrounds/sonar.jpg"

mine : 

[org.mate.background]
picture-filename='/usr/share/backgrounds/manjaro.jpg'

more example like on Ghostbsd mate : https://github.com/GhostBSD/mate-installed-settings/blob/master/schemas/92_org.mate.desktop.background.gschema.override
