### ISSUE TITLE
work on sonar-mate settings and profile

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#53]
@coffeeking 
Here's where I currently am with my suggestions for the Mate-edition:
- changed gtk-theme to **Adwaita-Manjaro-dark**
- changed xcursor-theme to **Breeze**
- panel height changed to 30px with bright icons and text on dark background
- font-size changed to 11px everywhere and in Terminal to 12px
- changed **gnome-terminal** profile to 12px white font on black
- changed notification theme to **Coco**
- moved the sound-theme to a new package **sonar-sound-theme**. Advantage of packages is always that we avoid future file conflicts, we are able to maintain existing installs via updates and also we make these features available to anyone, not just on fresh installs.
- default panel is now set in gsettings to **sonar** which is defined in **/usr/share/mate-panel/layouts/sonar.layout**. I've left that in the profile for now for easier modifications but I suggest that later we move that to a package, too.
- added to the panel: main-menu and launcher for **firefox** on the left side, moved the 'show desktop'-applet to the right side next to workspace-switcher and the rest.
- There appears to be some bug with setting the custom keybindings via gsettings override. It does work with direct gsettings commands, though, and so I cooked up this more or less creative workaround: You'll find a launcher **.config/autostart/set_keybindings.desktop** calling a script that sets the custom keybindings and creates a lockfile to make sure that in case the user changes the keybindings they will not be reset on next login. See **/usr/bin/set-keybindings** ;) Since all this is part of the settings package we can change or remove that stuff easily anytime we find a proper solution for it. In any case, the keybindings are now finally working! :laughing: 
- launchers in autostart need to be executable btw. I changed that for your login-sound launcher.

Remaining issues:
- for some reason the volume adjustment in the autostart appears still not to be working. The script does what it should but apparently the launcher is not working. I'll investigate that further. @Kirek , any idea?
- for me the sound is completely distorted - I had that already in earlier sonar-ISOs and I wonder if it's somehow a problem just on my system? Weird though because I am running this in virtualbox and never have this issue with other ISOs. Do you have any idea?
- **brltty.service** throws an error during boot-time and fails to start. Maybe **brltty** simply needs a package update? Systemctl output is below.

Meanwhile maybe you'd like to build a test ISO and let me know how you like the changes and if you'd like this or that differently or reverted.
```
$ systemctl status brltty.service
● brltty.service - Braille Console Driver
   Loaded: loaded (/usr/lib/systemd/system/brltty.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2016-03-28 11:56:17 UTC; 2h 3min ago
  Process: 207 ExecStart=/usr/bin/brltty --pid-file=/run/brltty.pid (code=exited, status=0/SUCCESS)
 Main PID: 270 (code=killed, signal=ABRT)

Mar 28 11:56:16 sonar brltty[270]: cannot load speech driver: /usr/lib/brltty/libbrlttysauto.so
Mar 28 11:56:16 sonar brltty[270]: speech driver not loadable: auto
Mar 28 11:56:16 sonar brltty[270]: /usr/lib/brltty/libbrlttysspeech-dispatcher.so: cannot open shared object file: No such file or directory
Mar 28 11:56:16 sonar brltty[270]: cannot load speech driver: /usr/lib/brltty/libbrlttysspeech-dispatcher.so
Mar 28 11:56:16 sonar brltty[270]: speech driver not loadable: speech-dispatcher
Mar 28 11:56:17 sonar brltty[270]: eSpeak Speech Driver: version 0.3
Mar 28 11:56:17 sonar brltty[270]: Linux Screen Driver:
Mar 28 11:56:17 sonar systemd[1]: brltty.service: Main process exited, code=killed, status=6/ABRT
Mar 28 11:56:17 sonar systemd[1]: brltty.service: Unit entered failed state.
Mar 28 11:56:17 sonar systemd[1]: brltty.service: Failed with result 'signal'.
```

**Comment by oberon2007** [comment]
Well, it's not surprising that the pulseaudio launcher is not working in mate since it cointains
``OnlyShowIn=XFCE;`` :wink:
Also I think ``Version=0.9.4`` is something that should not  be there - will check that again...

**Comment by oberon2007** [comment]
[freedesktop](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys) says about ``Version=``:

> Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.0. Note that the version field is not required to be present. 

So I think the line should just be removed or we use ``Version=1``
@Kirek could you please fix that for us?
We'll either have to make the launcher visible for all editions or we need a custom one for sonar that shows in Mate and Gnome... Not sure what will be best.

**Comment by Kirek** [comment]
https://github.com/manjaro/manjaro-tools-livecd/commit/5d8b2d2d71396f81822757c1616ce3f20bc88b69
Like this?

**Comment by coffeeking** [comment]
hi
All these ideas are fantastic. I was going to suggest packaging the
sonar sound theme, but I got overworked and just plain forgot about it
lol. Just about to crash for a while, so I'll continue when I'm up for
the day.
Thanks
Kendell Clark


Bernhard Landauer wrote:

**Comment by coffeeking** [comment]
hi
I particularly like the white text on a  black background, it gives our
high contrast users an easier time viewing things without them having to
set things themselves. I'd have done it myself if I knew how, but a lot
of those thinge you did I didn't even know could be done.
Thanks
Kendell Clark


Bernhard Landauer wrote:

**Comment by oberon2007** [comment]
Ok, great! :)
The issue with **brltty** unfortunately was not solved by package update 
- I don't know what we can do about that right now...
Sound in general appears to be ok for me now after I switched my 
virtualbox to virtual Intel HD sound card instead of ICH AC97.
