### ISSUE TITLE
if its ok wil do Mate-only..

### ISSUE THREAD

**Issue by ringo32** [manjaro/desktop-settings#6]
hi, just back on git :)

bit cooled down .. but wil do only Mate because also interested on one way and two desktops is always ..,  but hemm....this case will work on mate further..

**Comment by oberon2007** [comment]
Hi Ringo! :)
I hope it's still ok that I do Cinnamon for now - I have already played quite a lot with it, tweaked it to my preferences and sorted out all the gsettings schemas stuff ;)

**Comment by ringo32** [comment]
was there a live part in it also ?

**Comment by ringo32** [comment]
oberon think about the .cinnamon hidden folder in skel the config is not so importand to have it in skel, since most config is in dconf also by the way.. does  desktop-settings also live ? im curius

**Comment by ringo32** [comment]
thinks like inhibit is importand to stick on the panel videos :) but if you use 'new' configs then yeah must stick in it ? but i guess .local

**Comment by udeved** [comment]
Btw, cinnamon runs fine with openrc.
I tested yetserday, but we would need a ck override schema that disables logind.

**Comment by ringo32** [comment]
thats i didnt know because of lack of suspension, mate works also nicely with openrc, only know have upower mate-session-manager in aur if it to do on gschema i dont know.

**Comment by udeved** [comment]
ck2 runs with upower since 1.0.0, it just needs pm-utils installed.

**Comment by oberon2007** [comment]
I put everything in gsettings schemas now and removed dconf. Works perfectly :-)

**Comment by ringo32** [comment]
what the hell is manjaro-base-skel ?  all double file conflicts ?

**Comment by ringo32** [comment]
also gschemas in live-settings how to do ?

**Comment by ringo32** [comment]
stil have configure mate-panel layout proper in mate

**Comment by udeved** [comment]
Why do you need special schamas in live session?

**Comment by ringo32** [comment]
switch of the lock..

but i am just experimenting right now only...

**Comment by ringo32** [comment]
its irritating when lock screen comes up

**Comment by ringo32** [comment]
have just re-order the pkgbuild for my self right now..

**Comment by ringo32** [comment]
Only i want to research my self the system affect's if a Desktop-setting get updated, prons of cons of use of too much Gschema setting.....otherwise dconf will still needed in skell only minimalize it in fact. have for my self the path too gschema changed to shared, so manjaro.layout works properly and sitting by the other layouts  as mate-monitor customisation..
