### ISSUE TITLE
omf file not initializated

### ISSUE THREAD

**Issue by Ste74** [manjaro/desktop-settings#62]
Hi @Chrysostomus in your bspwm profile is present a file called omf .. what is ? Is possible delete it ? Is not initializated for github .. You found it in /skel/.local/share :smile:

**Comment by Chrysostomus** [comment]
Oh-my-fish. I made a mistake when adding it initiallym it is coming back later.

**Comment by Ste74** [comment]
Done
https://github.com/manjaro/desktop-settings/commit/97fdac24e570816f9c989e7885525a82aa8818e6
