### ISSUE TITLE
manjaro-openbox-settings conflicts none

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#64]
I don't have the time right now to check this further, but it just turned out that **manjaro-openbox-settings** package doesn't conflict properly, meaning: not at all! :stuck_out_tongue_winking_eye: 
```
$ pacman -Si manjaro-openbox-settings
Repository      : community
Name            : manjaro-openbox-settings
Version         : 20160405-1
Description     : Manjaro Linux openbox-minimal settings
Architecture    : any
URL             : https://github.com/manjaro/desktop-settings
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : manjaro-base-skel  obmenu-generator  tint2  feh
                  openbox-themes  vertex-maia-themes  maia-icon-theme
                  maia-wallpaper
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 17.75 KiB
Installed Size  : 68.00 KiB
Packager        : Artoo <artoo@manjaro.org>
Build Date      : Tue 05 Apr 2016 23:39:58 CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
Please someone have a look!

**Comment by udeved** [comment]
Should be fine, afaik, the package is coinstallable as the almost only one of the settings packages.

**Comment by oberon2007** [comment]
Well since it contains a **/etc/skel/.gtkrc-2.0** it will conflict with pretty much all WMs ... :wink: 
https://forum.manjaro.org/t/manjaro-i3-16-06-rc-stable/537/15)
``manjaro-openbox-settings: /etc/skel/.gtkrc-2.0 already exists in filesystem``

**Comment by udeved** [comment]
If we only could agree on the gtkk theme for manjaro, and this file could go in base skel.

**Comment by udeved** [comment]
This is no good move I believe.
I haven't had time to build a test iso, but my lxqt-minimal settings package depends on openbox-settings. Note, lxqt-minimal already conflicts with "desktop-settings" packages, so this make likely the depend screwed up, and OB settings will also conflict with lxt-minimal.

**Comment by oberon2007** [comment]
Oh I see, sorry! Now I understand! :stuck_out_tongue_closed_eyes: beh. I guess we should the just have it conflict with other WMs with conflicting files. I think i3, JWM and bspwm should do.

**Comment by oberon2007** [comment]
plus fluxbox

**Comment by oberon2007** [comment]
I'll just do that for now because I had already pushed the other package. Maybe you will come up with a more ingenious solution later :wink: But I think like that everything should work at least...

**Comment by oberon2007** [comment]
**.xinitrc** will conflict with xfce, too ...

**Comment by udeved** [comment]
This is why I would favour a modular package system for that, or we finally agree to use one theme and iconset for manjaro, so this could be shared package. We simply have all to sit down again and find a better way to structure the settings packages, and split out shared stuff everybody uses.
xinitrc could be merged together, so we only need one such file for all DE.

I wouldn't be pleased if my next build fails due to this.

**Comment by oberon2007** [comment]
A **.xinitrc** more or less like [**this**](https://github.com/manjaro/desktop-settings/blob/master/community/i3/skel/.xinitrc) should work for everybody, right?

**Comment by udeved** [comment]
Yes.
I am pretty convinced, a big source of error is these files on the various editions.
Some of them are over customized and only work on certain environments.
If people run more than two DE on the system, this could lead to trouble.
Hence I am not happy with the many iso out, they are too specific and bring more disadvantages than advantages. We complicate a simple switch of DE with it, or to have multiple DE installed, which is a cake walk on other distros.

**Comment by oberon2007** [comment]
Editions which declare their themes via gsettings should also not be a big problem since they deploy their theming via override. The tilers can achieve a lot via **.Xresources**. Problematic as far as I see it are basically gtk2 settings and what keeps giving me headaches is xcursor settings - they are in all sorts of places and very inconsistent between toolkits. I still have no uderstanding how qt-apps pick their icon and cursor theme when used in a gtk surrounding...

**Comment by udeved** [comment]
Perhaps you should simply fiddle a bit with qt based DE.
Qt stuff follows the proven old ways of doing things, xdg compliant
The exception from the rule is gtk3, because it seems rather difficult to deploy gschema.override in ~.local/share/glib2...
But we are more taking about the .(dot) files in user home from skel
