### ISSUE TITLE
KDE fails launching after octopi upate (pacman -Syu)

### ISSUE THREAD

**Issue by f4wks** [manjaro/desktop-settings#65]
Hey there,

using manjaro on Hyper-V (Windows 10) KDE Desktop. When I am using "pacman -Syu" to update my system the system every time goes into "boot loop" after restart. Have tried this mutliple times (because I am restoring snapshot before update). I sadly don't have the knowledge to figure out what is wrong with the update. 

Also it's not a classic boot loop it looks like arch is trying to start kde but fails (deksop keeps beeing black). 

What I did:
- Launching TTY with CTRL+ALT+F2 works

---

journalctl -b : http://pastebin.com/pbQbxpsS
pacman.log : http://pastebin.com/B26cZEWY
Xorg.0.log : http://pastebin.com/Am1cVGjQ
list of updates: http://pastebin.com/aCZnijUh

Note: Also "same" thing happens to me on Arch with gnome as desktop:

https://bugs.archlinux.org/task/49430

**Comment by Ste74** [comment]
Is still open @f4wks ?

**Comment by philmmanjaro** [comment]
Will close it now.
