### ISSUE TITLE
Wayland has not been installed

### ISSUE THREAD

**Issue by RafaelAybar** [manjaro/desktop-settings#69]
In Manjaro KDE 16.0.3 with non-free controller, wayland was not implemented. Should I reinstall Manjaro with free controllers  to use it?. I used a Nvidia 960 with kde neon in Wayland with Nvidia drivers and it woreked.

**Comment by Strit** [comment]
What do you mean wayland is not installed?

Wayland is a dependency of xorg as far as I know, so it should be installed. You just might not have a wayland session in your login screen.

This can be fixed by installed the "plasma-wayland-session" package. Should not be default on the install media.

**Comment by Ste74** [comment]
Is still open @RafaelAybar

**Comment by philmmanjaro** [comment]
@RafaelAybar: If still an issue, please fill out a [new one](https://bugs.manjaro.org). Thx.
