### ISSUE TITLE
Lets organize wallpapers

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#7]
Lets have us organize wallpaper packages by adding a "manjaro-wallpapers" group for pacman.
Lets also remove old artwork, repackage if necessary.

**Comment by ringo32** [comment]
it would be nice idea if you do build 3 month cycle... unstick the manjaro wallpaper in Artwork,   then like Daniella Artwork contest , so every cycle so can be packaged if needed ?
pinpoint standard organisition Manjaro Artwork in a Package thats all.. if on a concencus like you Drawn in all edition in Iso..  the used wallpapers as example.. furtjer commuity expanding etc... in the (codename)-Manjaro-artwork ??

**Comment by oberon2007** [comment]
"**(codename)-Manjaro-artwork**" :+1:

**Comment by Ste74** [comment]
@udeved , @oberon2007 i have search in pkgbuild for desktop setting but not see 'depends=wallpaper-de' .. i think not like that .. if in a future user install desktop setting when login in the new de wallpaper is black :(

**Comment by udeved** [comment]
Ste, we currently don't have depends in the settings packages.
Plan is, once these packages are stable, we slap many depends on them.

eg manjaro-lxqt-settings depend on lxqt group

This would reduce the Packages-Lxqt list to basically just additional apps, the main DE packages would be pulled in by the settings package.
That's the idea.

**Comment by Ste74** [comment]
Ah ok .. so it sounds better :)

**Comment by oberon2007** [comment]
Blessed the person who then sets out to build this gigantic mountain of split packages with the depends for every DE on the planet in his chroot :open_mouth: :stuck_out_tongue:

**Comment by Ste74** [comment]
Bernhard .. only 30/35 min for de and for arc

**Comment by udeved** [comment]
Hopefully, this will be done by a build server in not too distant future.
But these packages can be built for repo with makepkg in may view.
They don't have makedepends.

**Comment by philmmanjaro** [comment]
So how many split packages we are talking now?

**Comment by udeved** [comment]
One that accepts 3-4 settings providers.
https://github.com/manjaro/packages-extra/commit/5af18ca4a7cfbfcfe96ba1738ea350b474aa2a6f

Not 'activated" yet in pkgname array.

**Comment by udeved** [comment]
But, I am not sure we should host these kind of additions in desktop-settings repo, at least we shouldn't let it grow out of hand.

**Comment by oberon2007** [comment]
Of course I am unexperienced, so I'm not really a good reference ;) but for my impression this huge desktop-settings PKGBUILD already gets quite confusing ... ;)
Maybe just better create a separate **nemo-settings** package and list it in the profiles that need it?

**Comment by oberon2007** [comment]
sorry, I meant to say **nautilus**! ;)

**Comment by udeved** [comment]
Do these 3 DEs all use nemo? 
I see a problem in that we don't build all the filemanagers that could have a provides to depend on for the filemanager addon.
Its basically pretty similar to my kde-servicemenu package on my github, but I only do it for dolphin.

**Comment by udeved** [comment]
all 3 nautilus then? :laughing:

**Comment by oberon2007** [comment]
I live too far from the sea :joy: Yes, deepin, gnome, budgie use nautilus.

**Comment by udeved** [comment]
So the package can depends on nautilus and should be put in a separate repo, or even just in the packagebuild dir of its new build.
Ins't there already a nautils addon in AUR that does this?

**Comment by oberon2007** [comment]
I don't understand, sorry. "in the packagebuild dir of its new build."?

**Comment by udeved** [comment]
well, the source array in the PKGBUILD would use a "local" source, that resides in same dir as the PKGBUILD:
Would be acceptable for just a script and laucher.

**Comment by oberon2007** [comment]
Ah. You mean the PKGBUILD of **desktop-settings**?
I just thought: create a pkg "nautilus-empty-file" or whatever in community repo and list it in Packages-{Deepin,Budgie,Gnome}

**Comment by udeved** [comment]
No, I mean this addon gets its own pkgbuild, and you deploy the two files in the pkgbuild dir.
Make the build depend on nautilus, and put it in packages-community I think.
We then remove the package and the source from desktop-settings repo.

**Comment by oberon2007** [comment]
I think we mean exactly the same thing actually :laughing: Don't we?

**Comment by udeved** [comment]
Right idea last post. :+1: 

The package has basically nothing to do with desktop-settings, its a nautilus extension.

**Comment by oberon2007** [comment]
Good. I'll create the package then in packages-community and add it to the three profiles, ok?

**Comment by udeved** [comment]
yes, I added the package already, just change the name to your new package name.
I'll remove it from desktop-settings.

**Comment by oberon2007** [comment]
ok
