### ISSUE TITLE
Error while trying to update `manjaro-bspwm-settings`

### ISSUE THREAD

**Issue by Vrakfall** [manjaro/desktop-settings#71]
Hello,

I'm using the bspwm version of Manjaro and whenever I try to update `manjaro-bspwm-settings`, I get the following error:

```fish
error: failed to commit transaction (conflicting files)
manjaro-bspwm-settings: /etc/skel/.config/fish/completions/fisher.fish exists in filesystem
manjaro-bspwm-settings: /etc/skel/.config/fish/fishfile exists in filesystem
manjaro-bspwm-settings: /etc/skel/Bspwm-beginners-guide.txt exists in filesystem
```

In my view, It feels related to #12.

Should I delete the files or does this mean there's something wrong with the package?

**Edit:** Oh and my current version is `20161208-1`.

**Comment by Ste74** [comment]
Is still open @Vrakfall ?

**Comment by philmmanjaro** [comment]
@Vrakfall: if this is still an issue, please open a [new one](https://bugs.manjaro.org).

**Comment by Vrakfall** [comment]
Sorry, I kinda forgot about this. ^^'
I don't remember having any more issue with it, even though I think I fixed it manually.
I guess it's solved.
