### ISSUE TITLE
Conflict when installing i3-manjaro

### ISSUE THREAD

**Issue by deb0ch** [manjaro/desktop-settings#73]
I just tried to install the package `i3-manjaro` using `pacman -S i3-manjaro`, but I get the following error:

```
[deb0ch@YoloCorp ~]$ sudo pacman -S i3-manjaro
:: There are 10 members in group i3-manjaro:
:: Repository community
   1) artwork-i3  2) conky-i3  3) dmenu-manjaro  4) i3-default-artwork  5) i3-gaps  6) i3-help  7) i3exit  8) i3status-manjaro  9) manjaro-cinnamon-settings  10) manjaro-i3-settings

Enter a selection (default=all): 
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: manjaro-cinnamon-settings and manjaro-i3-settings are in conflict
```
It appears that for some reason, `i3-manjaro` depends on both `manjaro-i3-settings` and `manjaro-cinnamon-settings`, which are apparently not compatible.

I worked around it by selecting only all dependencies excepts for the 9th, but this error puzzled me for a time.

Not sure at all that this is the place to report, please tell me where to report if this is the wrong place :smile_cat:

**Comment by oberon2007** [comment]
Ah. Of course ``manjaro-cinnamon-settings`` should not be a member of group ``i3-manjaro``. I'll fix that mistake. Meanwhile you can simply install 1-8 and 10 :wink: 
Thanks for reporting!
