### ISSUE TITLE
live-session.desktop autostart not working in Cinnamon

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#8]
```
[manjaro@manjaro-cinnamon ~]$ ls .config/autostart/
disable-dpms.desktop  manjaro-welcome.desktop
live-session.desktop  pulseaudio-ctl.desktop
```
As the title says, **desktop-items** script doesn't run at login. It does when I double-click the .desktop item in .config/autostart
**manjaro-welcome** launches fine.

**Comment by udeved** [comment]
Seems cinnamon specific problem then.

**Comment by oberon2007** [comment]
@ringo32 ? ideas?

**Comment by ringo32** [comment]
only live-session.desktop ?

**Comment by udeved** [comment]
See https://github.com/manjaro/manjaro-tools-iso-profiles/issues/113
 and

https://github.com/manjaro/desktop-settings/commit/09b42eeb79663a7c9c93e11b7eb15ffc4a3d9bd0

**Comment by ringo32** [comment]
i think disable-dpms also dont work :p

**Comment by coffeeking** [comment]
hi
Myself, I'd like to know who removed most of my icons, and why? I've 
just taken a look at sonar's desktop settings profile, and my docs 
symlinks were broken, along with my help icons being removed. Are these 
supposed to go somewhere else or be in another package? If so, I can 
work with them there but those icons were there for a reason. Sorry if I 
sound a little grumbly, haven't had my morning coffee yet lol. I'll be 
happy to work with the new setup, I just have to know what the new setup is.
Thanks
Kendell clark

**Comment by udeved** [comment]
Hi Kendell;

I removed the stuff and packaged your docs and help file in sonar-common.
I thought I had added it to your shared desktop list.
But you may suffer from same live desktop items gremlin as cinnamon, since its both gtk3 based profiles.
Hang on, I think we figured it out.

**Comment by coffeeking** [comment]
hi
Gotcha. I'll add that to the images. Again, sorry for the tone, got my 
coffee now.
Thanks
Kendell clark

**Comment by ringo32** [comment]
i dont know if its on Dconf level.... first of all i was in Live-session.. in cinnamon , i moved the desktop files to ~/.local/share/Desktop    with the install calamares thus and Hexchat, and made a symlink of the Hexchat Desktop file, with :+1: 
ln -s (hexchat desktop) ~/Desktop    .. so what i get is i right issue with a icon of nitrux with a lock... it become unusable... so the icon changed.... but i removed the symlink... and did  same with  :  ln -P (XXXX desktp file) ~/Desktop

and icon seemed to show and running. but i see -P is physical...

that was my thought about it... how did it with the documentation symlink, that is working as should ?

**Comment by oberon2007** [comment]
Well for some reason it seems to work for openint a .pdf file but not to launch an application by itself.
Can we not simply create physical .desktop files in **manjaro/Desktop**?

**Comment by udeved** [comment]
Desktop folder is not localized.
Its Schreibtisch in German.

The entire thing works with gnome btw, I just tested.

What happens if you addthis to override?
~~~
[org.gnome.desktop.background]
show-desktop-items="true"
~~~

**Comment by oberon2007** [comment]
Sorry, I don't understand what you localized means in that sense. Copying the .desktop files to Desktop does work in any case. Why do we need them as symlinks?
![icons](https://cloud.githubusercontent.com/assets/11800714/12494788/8929b496-c08c-11e5-9771-a7a91de569be.png)

**Comment by oberon2007** [comment]
``show-desktop-items="true"`` doesn't help with the symlink icons. It only has the effect that the background image set in org.gnome.background overrides org.cinnamon again ;)

**Comment by udeved** [comment]
The Desktop folder is not localized in Name.
It only works with your proposal for english.

I don't see why we should do it differently to before, we do the same but with package.
It did work before, its a matter of setting dconf anfter the dconf blob got deleted.

**Comment by oberon2007** [comment]
![dconf](https://cloud.githubusercontent.com/assets/11800714/12494995/7bc750be-c08d-11e5-9102-e4cd41048921.png)

**Comment by coffeeking** [comment]
hi
I noticed that. Now I can't release new sonar images until an override 
schema is generated
Thanks
Kendell clark

**Comment by oberon2007** [comment]
@udeved , I get it now with localization. But why can you not simply in the **desktop-items** script replace `ln -sf' with 'cp' ?

**Comment by oberon2007** [comment]
Oops, doesn't work either! why??
![cp](https://cloud.githubusercontent.com/assets/11800714/12495170/9047ec5a-c08e-11e5-841d-287cfcea8a39.png)

**Comment by udeved** [comment]
I am on the way doing that. The symlink is not the problem I think.

**Comment by oberon2007** [comment]
icons are displayed when they are executable!! But why is your preference for the symlinks anyway? I think proper items look nicer ;)

**Comment by oberon2007** [comment]
chmod +x is the secret! :laughing: 
![chmod x](https://cloud.githubusercontent.com/assets/11800714/12495263/128e1e5a-c08f-11e5-9a02-9d2742359cd6.png)

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/commit/2aa36f777aa778f8119dbbc15611a1b1aef97e1c

Packages in unstable

**Comment by oberon2007** [comment]
Yes. That should work. It's what I have just tested here. Thanks! :)
We just still need a solution for the autostart...

**Comment by udeved** [comment]
what autostart?

**Comment by oberon2007** [comment]
for the script. autostart in **~/.config/autostart** didn't work. Did I miss something?

**Comment by udeved** [comment]
It did work, I guess the gtk DEs have trouble with permissions, so the icons were not displayed.
Hence your trashcan had a gap to other icons, due to "invisible" icons.

This is what went on I think

**Comment by oberon2007** [comment]
The gap is always there. Seems to be an oddity of cinnamon. So you're going to chown the launchers?

**Comment by udeved** [comment]
Already happened, unstable has the new live-skel package.

**Comment by oberon2007** [comment]
I'm not convinced about the ownership to be the problem. When I run the script manually the items are created and owned by root. Still they are displaying! I think the script never runs.
Ok. will try the new package.

**Comment by udeved** [comment]
Have you build it yet? Less talk, more try. :tongue:

**Comment by ringo32** [comment]
had issues with hexchat in old state, at o turn user rights te menu and copy it to the profiles in 'old' state

did a livecd session do ln -s ~/.local/share/Desktop/*.desktop ~/Desktop   it showed fine in my livecd, its 1 permision :)


what is difference of ln -P or ln -s ? is -P as copy ?

**Comment by ringo32** [comment]
had also before always on the desktop files had to right is

**Comment by oberon2007** [comment]
script is not autostartet still.
![new_package](https://cloud.githubusercontent.com/assets/11800714/12496081/c5aac8b8-c093-11e5-921f-107b433bdf98.png)

**Comment by udeved** [comment]
Yet it shows as started in the cinnamon settings.

**Comment by oberon2007** [comment]
But you can see in the filebrowser window in the screenshot that ~/Desktop is empty.

**Comment by udeved** [comment]
Right, yet the autostart gui shows desktop-items as started, and they are in ~/.config/autostart

**Comment by philmmanjaro** [comment]
So what is the exact error on this one?

**Comment by udeved** [comment]
For some reason, cinnamon doesn't seem to find the copy source, so nothing gets copied to desktop.

**Comment by oberon2007** [comment]
That's not completely correct, because when you launch **~/.config/autostart/live-session.desktop** manually the items are copied fine. Just autostarting it doesn't work!

**Comment by oberon2007** [comment]
The autostart gui lists the items. That doesn't mean necessarily that they are autostarted successfully, does it?

**Comment by udeved** [comment]
Try to find in nemo /usr/share/applications/calamares.desktop ^^

**Comment by oberon2007** [comment]
I was not able to find more information on autostarting in Cinnamon ... :-| Maybe it needs more than just adding the items to ~/.config/autostart? In case of **manjaro-welcome** it seems to be sufficient. Or does checking the box in the Manjaro Welcome GUI do more than that, maybe??

**Comment by oberon2007** [comment]
Maybe the launchers need some ``show in`` entries?

**Comment by udeved** [comment]
No seriously, I think this is a nemo problem handling overlayfs.
Nemo doesn't have the launchers in /usr/share/applications, so nemo uses the DE layer, not a joined live layer.

**Comment by udeved** [comment]
I think nemo is being used like nautilus on gnome to manager desktop.

**Comment by oberon2007** [comment]
The reason is the .desktop file.
I don't know yet which entry is the crucial one, but this one works in autostart:
```
[Desktop Entry]
Exec=desktop-items
Name=desktop-items
Comment=Live session desktop items
Type=Application
Terminal=false
Categories=GNOME;GTK;System;
StartupNotify=false
Icon=gtk-info
```
I just used the manjaro-welcome one as a template.
Maybe an icon needs to be specified or something stupid like that. Or it's the categories.
Will try to find out what makes the difference. :)

**Comment by udeved** [comment]
We need more minimal profiles. Its a pain in the a** these big profiles.

**Comment by udeved** [comment]
It works in gnome, I just tested.

perhaps you should switch to gnome backend for desktop and enable show-desktop-icons there, and set also background in org.gnome.desktop.background.

**Comment by oberon2007** [comment]
It's a lot simpler than that: Just remove the line ``Version=16.01`` and the autostart works :laughing:

**Comment by oberon2007** [comment]
``Version=1`` works, too, ``Version=1601`` doesn't - somehow a weird syntax problem.
Well, we can simply lose the version number there if it solves our problem, right? :)

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/commit/f3e0cc377437edffc6261d8a1fa324c39f6c878b

Can you build entire desktop-settings pls?

**Comment by oberon2007** [comment]
ok

**Comment by udeved** [comment]
I have added gnome, mate and minimal profiles

**Comment by oberon2007** [comment]
good ;)
right, this issue is solved - what a day...
good night, sir!
