### ISSUE TITLE
schema override

### ISSUE THREAD

**Issue by udeved** [manjaro/desktop-settings#9]
Is there an order for sections and keys to keep?
Does somebody know?

I don't get mate or gnome to talk in sonar, but accessibility is nicely activated as separate menu.

**Comment by oberon2007** [comment]
I think the order doesn't matter.

**Comment by udeved** [comment]
Hmm, perhaps we got to play around with the weighting of the override, even though its already highest with 99.
Some sonar settings don't get activated by default.

**Comment by ringo32** [comment]
mayby is 99 To high :) if you plan a livecd gschema like to make lock screen work at first hand... lockely in livecd lockscreen works... so it stil enabled to go intoo lock..

99 get to high on number, likely a gschema for a livesession need a higher number to disable lockscreen as example
